# Configuration LDAPS pour Grafana
[[servers]]
host = "10.0.0.10"
port = 636              # Port LDAP SSL
use_ssl = true
start_tls = false
ssl_skip_verify = false

#Certificat CA
root_ca_cert = "/etc/grafana/certs/ca.crt"

# Utilisateur
bind_dn = "cn=admin,dc=usine,dc=local"
bind_password = "adminldap"

# Filtre de recherche des utilisateurs pour trouver les membres du groupe peaple dans l'annuaire LDAP *fichier users.ldif
search_filter = "(cn=%s)"
search_base_dns = ["ou=People,dc=usine,dc=local"]

# Format d'enregistrement des utilisateurs dans l'annuaire LDAP
[servers.attributes]
name = "givenName"
surname = "sn"
username = "cn"
member_of = "memberOf"
email =  "mail"